version: '3.8'

services:
  db:
    image: postgres:17.1-alpine
    container_name: library_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - library-network

  app:
    build:
      context: .
    container_name: library_app
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - library-network

volumes:
  db_data:

networks:
  library-network:
    driver: bridge
