# version: '3.8'

services:
  database:
    image: postgres:14
    build:
      context: .
      dockerfile: ./postgre-db/Dockerfile
    restart: always
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pglogs:/var/log/postgresql

    networks:
      - app-network
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-U',
          '${POSTGRES_USER}',
          '-d',
          '${POSTGRES_DB}',
          '-h',
          'database',
          '-p',
          '${POSTGRES_PORT}',
        ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
 - '${PORT}:${PORT}'
     env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./src:/usr/app/src
        - /app/node_modules
    networks:
      - app-network

volumes:
  pgdata: {}

networks:
  app-network:
    driver: bridge
